### ISSUE TITLE
Unable to install dotnet472 - Broken since Wine 5.12

### ISSUE THREAD

**Issue by raitono** [Lazalatin/space-engineers-dedicated-ubuntu-docker-server#18] opened 2020-09-10 15:36 UTC
Is there a workaround for this issue? My `docker-compose up` fails miserably with these messages:
![image](https://user-images.githubusercontent.com/4654099/92755250-a5f29980-f359-11ea-8319-f79dcf9d5184.png)

There is a bug on WineHQ that seems to show that .Net 4.0+ has been failing on Wine since 5.12 and offers no workaround.
[WineHQ](https://bugs.winehq.org/show_bug.cgi?id=49532)

**Comment by Lazalatin** [comment] 2020-09-10 21:44
Well, my (still running) container is quite old now. 😅 
I never tested to create a never instance of it.
I will try to pin the wine version to a working one, as soon as I can. If you like, you may also provide a PR doing so 😉

**Comment by Sushiman42** [comment] 2020-09-26 05:54
Really hoping for an update on this one, I'm getting the same crash.

**Comment by halkeye** [comment] 2020-09-30 03:33
I have a PR that pins wine, i'm going to test it for a day or two, and then submit it on the 1st for hacktoberfest

**Comment by halkeye** [comment] 2020-09-30 06:30
I give up, anyone that wants it to compile can use my patch, but i can't get it running
https://github.com/Lazalatin/space-engineers-dedicated-ubuntu-docker-server/pull/19

**Comment by Lazalatin** [comment] 2020-10-05 19:54
@halkeye Your PR works as intended in terms of getting to build the container. Running it is another issue. I had many pains with that matter myself. Do not really now how to stabilize that, right now... :/

**Comment by Lazalatin** [comment] 2020-10-05 21:11
This was fixed by adding commit 12d72d6d3346c8d488f39f2da5eb11f826cd954e

**Closed by Lazalatin** 2020-10-05 21:11 UTC
